export const SCENE_ASSET_LIST = [
  {
    type: 'coaster',
    name: 'coaster',
    src: '/images/coaster.png',
    model: '/objects/coaster.glb',
  },
  {
    type: 'rail',
    name: 'straight',
    src: '/images/rail-straight.png',
    model: '/objects/rail-straight.glb',
  },
  {
    type: 'rail',
    name: 'curveLeft',
    src: '/images/rail-curve-left.png',
    model: 'objects/rail-curve-left.glb',
  },
  {
    type: 'rail',
    name: 'curveRight',
    src: '/images/rail-curve-right.png',
    model: 'objects/rail-curve-right.glb',
  },
  {
    type: 'rail',
    name: 'upSlopeFull',
    src: '/images/rail-up-slope-full.png',
    model: '/objects/rail-up-slope-full.glb',
  },
  {
    type: 'rail',
    name: 'downSlopeFull',
    src: '/images/rail-down-slope-full.png',
    model: '/objects/rail-down-slope-full.glb',
  },

  {
    type: 'rail',
    name: 'upStart',
    src: '/images/rail-up-start.png',
    model: '/objects/rail-up-start.glb',
  },
  {
    type: 'rail',
    name: 'upMiddle',
    src: '/images/rail-up-middle.png',
    model: '/objects/rail-up-middle.glb',
  },
  {
    type: 'rail',
    name: 'upEnd',
    src: '/images/rail-up-end.png',
    model: '/objects/rail-up-end.glb',
  },
  {
    type: 'rail',
    name: 'downStart',
    src: '/images/rail-down-start.png',
    model: '/objects/rail-down-start.glb',
  },
  {
    type: 'rail',
    name: 'downMiddle',
    src: '/images/rail-down-middle.png',
    model: '/objects/rail-down-middle.glb',
  },
  {
    type: 'rail',
    name: 'downEnd',
    src: '/images/rail-down-end.png',
    model: '/objects/rail-down-end.glb',
  },
  {
    type: 'item',
    name: 'bench',
    src: '/images/bench.png',
    model: '/objects/bench.glb',
  },
  {
    type: 'item',
    name: 'iceCreamCar',
    src: '/images/ice-cream-car.png',
    model: '/objects/ice-cream-car.glb',
  },
  {
    type: 'item',
    name: 'bumperCar',
    src: '/images/bumper-car.png',
    model: '/objects/bumper-car.glb',
  },
  {
    type: 'item',
    name: 'ferrisWheel',
    src: '/images/ferris-wheel.png',
    model: '/objects/ferris-wheel.glb',
  },
  {
    type: 'item',
    name: 'coffeeCart',
    src: '/images/coffee-cart.png',
    model: '/objects/coffee-cart.glb',
  },
];
